"""init

Revision ID: c0763e4d9abf
Revises: 
Create Date: 2025-11-16 19:56:33.854589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0763e4d9abf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('counter_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_counter_id'), 'sleep_counter', ['id'], unique=False)
    op.create_index(op.f('ix_sleep_counter_name'), 'sleep_counter', ['name'], unique=True)
    op.create_table('sleep_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('awake_start', sa.DateTime(), nullable=True),
    sa.Column('sleep_start', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sleep_end', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_entries_id'), 'sleep_entries', ['id'], unique=False)
    op.create_index(op.f('ix_sleep_entries_sleep_end'), 'sleep_entries', ['sleep_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleep_entries_sleep_end'), table_name='sleep_entries')
    op.drop_index(op.f('ix_sleep_entries_id'), table_name='sleep_entries')
    op.drop_table('sleep_entries')
    op.drop_index(op.f('ix_sleep_counter_name'), table_name='sleep_counter')
    op.drop_index(op.f('ix_sleep_counter_id'), table_name='sleep_counter')
    op.drop_table('sleep_counter')
    # ### end Alembic commands ###
